# Generated by Django 2.2.1 on 2019-05-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_answers_story_storydetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_date',
        ),
    ]
