# Generated by Django 2.2.1 on 2019-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_story_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='storydetail',
            name='fisrt',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
