# Generated by Django 2.2.1 on 2019-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190527_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='storydetailid',
            new_name='storydetail',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='storyid',
            new_name='story',
        ),
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
